name: Hello World

on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, World! 👋"
      
      - name: Show event name
        run: echo "Event: ${{ github.event_name }}"
      
      - name: Show branch
        run: echo "Branch: ${{ github.ref }}"
