name: Scheduled Tasks

on:
  schedule:
    # Run at 2 AM UTC every Monday
    - cron: '0 2 * * 1'
    # Run at 6 AM UTC every day
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  daily-checks:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Check dependencies for updates
        run: |
          echo "Checking for dependency updates..."
          # npm outdated
          # Your dependency update logic here
      
      - name: Run security audit
        run: npm audit
      
      - name: Cleanup old artifacts
        run: |
          echo "Cleaning up old files..."
          # Your cleanup logic here
      
      - name: Generate report
        id: report
        run: |
          report="Daily maintenance completed at $(date)"
          echo "report=$report" >> $GITHUB_OUTPUT
      
      - name: Send notification
        if: always()
        run: |
          echo "Status: ${{ job.status }}"
          echo "Report: ${{ steps.report.outputs.report }}"
          # Send to Slack, email, etc.

  weekly-cleanup:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.run_number % 7 == 0
    
    steps:
      - name: Clean up old releases
        run: echo "Running weekly cleanup..."
