name: Deploy Nginx Static Site

on:
  push:
    branches:
      - main
    paths:
      - 'nginx/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: echo ${{ github.actor }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: true
          tags: ghcr.io/${{ github.actor }}/${{ github.repository }}/nginx:latest

    # Optional: Deploy to a cloud service like Azure Container Instances or similar
    # For demo, just build and push. Add deployment steps as needed.
