name: Deploy Express App via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - run: pnpm --filter express-api install
      - run: pnpm --filter express-api build # if needed

      - name: Copy built files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          target: '${{ secrets.DEPLOY_PATH }}/expressapi'
          source: 'apps/express-api/dist/*'
          strip_components: 3

      - name: Copy package.json to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          target: '${{ secrets.DEPLOY_PATH }}/expressapi'
          source: 'apps/express-api/package.json'
          strip_components: 2

      - name: Install dependencies and restart app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}/expressapi
            pnpm install --prod
            pm2 restart expressapi || pm2 start index.js --name expressapi  # adjust entry point if needed
